spring.application.name=GritUthyrningAB
server.port=8081

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/pgdatabasegrit
spring.datasource.username=pguser
spring.datasource.password=pgpassword